{{ if .Values.server.enableTLS }}
{{- $altNames := list (printf "%s.%s" (include "kwok.fullname" .) .Release.Namespace) (printf "%s.%s.svc" (include "kwok.fullname" .) .Release.Namespace) "localhost" }}
{{- $ca := genCA (include "kwok.fullname" .) 365 -}}
{{- $cert := genSignedCert (include "kwok.fullname" .) nil $altNames 365 $ca -}}

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "kwok.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kwok.labels" . | nindent 4 }}
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end}}