apiVersion: v1
kind: Service
metadata:
  name: {{ include "kwok.fullname" . }}
  labels:
    {{- include "kwok.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.server.port }}
    protocol: TCP
    targetPort: {{ .Values.server.port }}
  selector:
    {{- include "kwok.selectorLabels" . | nindent 4 }}
  type: ClusterIP
